### ISSUE TITLE
rooms bridged to Telegram keep getting deleted and recreated, room ID changes all the time

### ISSUE THREAD

**Issue by evakdev** [vector-im/mautrix-telegram#57]
### Issue

The issue is with my telegram rooms in matrix. Some of them (not all) keep getting closed and recreated everyday. The messages are synced, but the room id changes every time. The id change prevents me from being able to identify rooms in my project, and sometimes creates unnecessary notifications. In addition, any alias I had set for the room is no longer present on the new room. 
This happens at least once a day, sometimes more. 

I’ve checked the perms on both “healthy” (not getting recreated everyday) and problematic rooms in telegram, and haven’t been able to find any specific situation that would make these rooms unique. It seems to be completely random. Sometimes problematic rooms suddenly become healthy, and sometimes a room that was okay becomes faulty. Sometimes the rooms get recreated on their own, and sometimes I have to manually sync them by sending the “sync” command to the bridge. I can't figure out what's causing it.

### Expectation 
To find out what is causing this, and figure it how to prevent the room ID from changing. Since the ID is what every single one of API endpoints work with, I need it to not stay unique and reliable, just as Whatsapp rooms are. 

### System
I am using Element One as my server and use the telegram bridge hosted there.

### Logs
Here are the [debug logs](https://github.com/vector-im/mautrix-telegram/files/10777334/rageshake.zip) provided to me by Element Web. Since I don't have admin access to the homeserver, this is all the debug logs I've got. Hopefully its enough. 

I would greatly appreciate anything that can help me figure this out. 
Thank you in advance for your help.

**Comment by Half-Shot** [comment]
Heya, from the debug logs it looks like you are using one.ems.host. While the report is fantastic (thanks!), we'd appreciate you giving us a ping on `ems-support@element.io` so we can check this out. It looks like you reported the bug upstream in https://github.com/mautrix/telegram/issues/894, and we can take it from there and provide logs.

**Comment by evakdev** [comment]
Hello. I sent an email with the info you requested, but it looks like the issue already got fixed on the upstream repo! Would you be so kind to update this repo too? Thank you again!
